/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_micronet_sampleapp_SerialPort_open
        (JNIEnv *, jclass, jstring, jint);


/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_micronet_sampleapp_j1708Port_DeviceOpen
    (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    config
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_micronet_sampleapp_SerialPort_config
    (JNIEnv *, jobject,jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_micronet_sampleapp_SerialPort_close
    (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_com_micronet_sampleapp_j1708Port_close
    (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif